[metadata]
name = simd-blend-modes
version = 1.1.0
description = SIMD-accelerated blend modes
license = MIT

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.9
install_requires =
    numpy
include_package_data = True

[options.package_data]
simd_blend_modes = *.pyi, py.typed

[options.packages.find]
where = src
